# Generated by Django 5.1 on 2024-11-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=100)),
                ('acta_de_nacimiento', models.CharField(max_length=100)),
                ('numero_celular', models.CharField(max_length=10)),
                ('rfc', models.CharField(max_length=100)),
                ('id_sucursales', models.CharField(max_length=6)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
